movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns=[
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.movie_add,name='movie_add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='pics')
    def __str__(self):
        return self.name

movieapp/views.py
from django.http import  HttpResponse
from django.shortcuts import render, redirect

from .form import MovieForm
from .models import Movie


#Create your views here
# def demo(request):
#    return HttpResponse("hello")
#
def index(request):

    movie=Movie.objects.all()
    context={
       'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})


def movie_add(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})


def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieapp/templates/add.html
{% extends 'base.html' %}
{% block body %}
<center>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <br>
  <br>
  <h1 align="center">Add Your Movie Details here......</h1><br>
  <input type="text" name="name" placeholder="Enter the film name"><br><br>
  <input type="text" name="desc" placeholder="Enter the description"><br><br>
  <input type="text" name="year" placeholder="Enter your year"><br><br>
  <input type="file" name="img"><br><br>
  <input type="submit"><br>

{% endblock %}
</center>
</form>

movieapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">



    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'styles.css' %}">


</head>
<body>

<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#" >

     Online Movie Store
  </a>

</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieapp/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
  {% csrf_token %}
  <h1>Do you want to delete</h1>
  <input type="submit">
  {% endblock %}
</form>

movieapp/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<center>
    <br>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-md-6">

        <img src="{{movie.img.url}}" width="250" height="250">

    </div>
    <div class="col-md-6">
        <h2>{{movie.name}}</h2>
        <h3>{{movie.desc}}</h3>
        <h4>{{movie.year}}</h4>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
    </div>
            </div>
    </div>
{% endblock %}
    </center>
</body>
</html>

movieapp/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<center>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>
  </center>
{% endblock %}

movieapp/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}<hr>
        <div class="cal=md-3">
            <div class="card" style="width: 18rem;" height="250">
                <img class="card-img-top" src="{{i.img.url}}"  height="250" width="250">
    <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
<!--    <p class="card-text"></p>-->
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">show details</a>


  </div>
</div>

        </div>

       {% endfor %}
    </div><br>
<center>
    <button class="btn btn-warning" onclick="window.location.href = 'http://127.0.0.1:8000/add/';" name="add_movie" >
  Add Movie
 </button>
    </center>


</div>

<!--<a href ="add.html">-->

{% endblock %}